### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by hushengNo1** [usercao/ice-test#2]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/22570190/182318675-1f51bf5e-bbd9-458d-b74e-24e03d958df1.png">

**Comment by usercao** [comment]
已修复`git pull`后重新执行`yarn install`

**Comment by hushengNo1** [comment]
> 已修复`git pull`后重新执行`yarn install`

谢谢，可以了，可以请教一下排查这种问题的具体思路吗？

**Comment by usercao** [comment]
这是上次测试一个`vite require`插件导致的错误，我知道是这个所以修改的很快，不知道可能需要从config配置文件挨个挨个查起了，这是我的问题，不用在意这个报错。

**Comment by hushengNo1** [comment]
> 这是上次测试一个`vite require`插件导致的错误，我知道是这个所以修改的很快，不知道可能需要从config配置文件挨个挨个查起了，这是我的问题，不用在意这个报错。

谢谢热心楼主
